kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
kubeadmConfigPatches:
  - |
    apiVersion: kubeadm.k8s.io/v1beta2
    kind: ClusterConfiguration
    dns:
      type: CoreDNS
      imageRepository: public.ecr.aws/eks-distro/coredns
      imageTag: v1.8.3-eks-1-21-4
    etcd:
      local:
        imageRepository: public.ecr.aws/eks-distro/etcd-io
        imageTag: v3.4.16-eks-1-21-4
    imageRepository: public.ecr.aws/eks-distro/kubernetes
    kubernetesVersion: v1.21.2-eks-1-21-4
nodes:
- role: control-plane
  extraMounts:
    - hostPath: /var/run/docker.sock
      containerPath: /var/run/docker.sock
